-- ROOTED.MY schema. Run in Supabase SQL Editor.

-- Leads (voluntary interest / waitlist)
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  email text not null,
  concern text default '',
  age_group text default '',
  budget text default ''
);

-- Products (shampoo catalog, seed + imported)
create table if not exists products (
  id bigint generated by default as identity primary key,
  barcode text,
  brand text,
  product_name text not null,
  category text,
  country text,
  ingredients_raw text,
  image_url text,
  source text,
  source_url text,
  price_range text,
  market_availability text,
  data_confidence text default 'medium',
  unique (source, source_url)
);

-- Ingredients (normalized INCI names)
create table if not exists ingredients (
  id bigint generated by default as identity primary key,
  inci_name text not null,
  common_name text,
  synonyms text,
  function text,
  description text,
  cas_number text,
  allergen_flag boolean default false,
  source text,
  unique (inci_name)
);

-- Product <-> Ingredient join with position on label
create table if not exists product_ingredients (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  ingredient_id bigint references ingredients(id) on delete cascade,
  ingredient_position int,
  unique (product_id, ingredient_id)
);

-- Hair profiles from questionnaire
create table if not exists user_hair_profiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  hair_texture text,
  hair_thickness text,
  scalp_type text,
  concerns text[] default '{}',
  wash_frequency text,
  wash_routine text,
  lifestyle text,
  sweat_frequency text,
  head_covering text[] default '{}',
  treatment_history text[] default '{}',
  heat_styling text,
  ingredient_preferences text[] default '{}',
  budget text,
  current_product text,
  personal_goal text
);

-- Assessments (paid results, gated behind payment_status)
create table if not exists assessments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  profile_id bigint references user_hair_profiles(id) on delete set null,
  current_product_id bigint references products(id) on delete set null,
  assessment_result jsonb,
  recommendations jsonb,
  payment_status text default 'pending',
  payment_provider text,
  payment_reference text
);
