import type { SeedProduct } from "./recommend";

// Legacy, unverified development examples. Product identity, variants,
// ingredients and prices must be sourced before any production use.

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "sunsilk-anti-hairfall",
    name: "Sunsilk Anti-Hair Fall",
    brand: "Sunsilk",
    category: "Shampoo",
    priceRange: "RM12–20",
    budgetMax: 20,
    market: "MY",
    tags: ["scalp_care", "strengthening", "damage", "gentle"],
    keyIngredients: ["Caffeine", "Keratin", "Glycerin"],
    normalizedIngredients: ["water", "sodium laureth sulfate", "cocamidopropyl betaine", "glycerin", "fragrance"],
    bestFor: ["Weak / shedding-prone hair", "Scalp care", "But is sulfate-based — may be stripping if used too often"],
    considerations:
      "Contains sulfates for strong lather; fine for most, but if your scalp is dry or sensitive, pair with conditioning or use a gentler formula on alternate washes.",
    why: "Balances strengthening actives with everyday cleansing, a practical pick for shedding concerns in our humid climate.",
  },
  {
    id: "pantene-3min-miracle",
    name: "Pantene Pro-V 3 Minute Miracle",
    brand: "Pantene",
    category: "Shampoo",
    priceRange: "RM14–24",
    budgetMax: 24,
    market: "MY",
    tags: ["damage", "smoothing", "conditioning", "protein"],
    keyIngredients: ["Pro-Vitamin B5", "Keratin", "Hydrolyzed Protein"],
    normalizedIngredients: ["water", "sodium laureth sulfate", "sodium lauryl sulfate", "fragrance", "panthenol"],
    bestFor: ["Damaged hair", "Smoothing", "Is sulfate-based — consider sulfate-free if you prefer gentler cleansing"],
    considerations:
      "Ribbons of conditioning ingredients help smooth rough hair. Not formulated as a scalp-focused or clarifying wash.",
    why: "Strong damage-repair positioning aligns with weak or rough hair concerns at an easy local price point.",
  },
  {
    id: "head-shoulders-gentle",
    name: "Head & Shoulders Gentle Care",
    brand: "Head & Shoulders",
    category: "Shampoo",
    priceRange: "RM15–25",
    budgetMax: 25,
    market: "MY",
    tags: ["scalp_care", "soothing", "gentle", "anti_dandruff"],
    keyIngredients: ["Zinc Pyrithione", "Aloe", "Glycerin"],
    normalizedIngredients: ["water", "sodium lauryl sulfate", "zinc pyrithione", "glycerin", "fragrance"],
    bestFor: ["Flaky / dandruff-prone scalp", "Oily scalp", "Sulfate-based cleansing"],
    considerations:
      "Contains zinc pyrithione (anti-dandruff active). It is cosmetic guidance only — not a treatment for skin conditions like psoriasis or seborrheic dermatitis.",
    why: "Targets flaking and scalp comfort, which many Malaysian users deal with alongside humidity and sweat.",
  },
  {
    id: "clearly-botanicals-hydration",
    name: "Clearly Botanicals Hydrating",
    brand: "Cleverly Botanicals",
    category: "Shampoo",
    priceRange: "RM18–28",
    budgetMax: 28,
    market: "MY",
    tags: ["natural", "gentle", "moisture", "sulfate_free", "silicone_free"],
    keyIngredients: ["Aloe Vera", "Rosemary", "Argan Oil"],
    normalizedIngredients: ["water", "coco glucoside", "cocamidopropyl betaine", "aloe barbadensis leaf juice", "glycerin"],
    bestFor: ["Dry / frizzy hair", "Sensitive scalp", "Sulfate-free minimalist preference"],
    considerations:
      "Mild plant-based surfactants good for frequent washing or sensitive scalps. May lather less than sulfate shampoos — that's normal.",
    why: "A sulfate-free, plant-based option that fits dry, frizzy, or sensitive profiles and the 'natural' preference group.",
  },
  {
    id: "living-proof-full",
    name: "Living Proof Full Shampoo",
    brand: "Living Proof",
    category: "Shampoo",
    priceRange: "RM90–120",
    budgetMax: 120,
    market: "INT",
    tags: ["volume", "lightweight", "thickening"],
    keyIngredients: ["PHA", "Amino Acid Blend", "Eucalyptus Extract"],
    normalizedIngredients: ["water", "sodium lauryl sulfate", "sodium laureth sulfate", "fragrance"],
    bestFor: ["Fine / flat hair", "Lack of volume", "Premium price tier"],
    considerations:
      "Gives body without heavy coating. Higher price; only fits premium budgets and volume-seeking goals.",
    why: "For volume and lift in fine hair, at a premium price point — matched only when budget allows.",
  },
  {
    id: "ogx-argon-oil",
    name: "OGX Argan Oil of Morocco",
    brand: "OGX",
    category: "Shampoo",
    priceRange: "RM25–40",
    budgetMax: 40,
    market: "MY",
    tags: ["moisture", "smoothing"],
    keyIngredients: ["Argan Oil", "Coconut Oil", "Keratin"],
    normalizedIngredients: ["water", "sodium laureth sulfate", "cocamidopropyl betaine", "argania spinosa kernel oil", "fragrance"],
    bestFor: ["Dry / rough hair", "Frizz", "Sulfate-free on label (verify variant)"],
    considerations:
      "Oils add moisture and tame frizz. Some variants of OGX contain sulfates despite the 'MO' marketing — check the label.",
    why: "A mid-priced hydrating option for dry and frizzy profiles with a smoothing finish in humid weather.",
  },
  {
    id: "seri-muka-booster",
    name: "SERI MUKA Hair Vitality Daily Booster",
    brand: "SERI MUKA",
    category: "Shampoo",
    priceRange: "RM20–32",
    budgetMax: 32,
    market: "MY",
    tags: ["natural", "scalp_care", "strengthening", "herbal"],
    keyIngredients: ["Ginseng", "Ginseng Extract", "Hair Vitality Complex"],
    normalizedIngredients: ["water", "sodium laureth sulfate", "cocamidopropyl betaine", "glycerin", "fragrance"],
    bestFor: ["Hair fall", "Scalp care", "Natural / herbal preference"],
    considerations:
      "Malaysian brand, widely available locally. Herbal positioning; still contains sulfates, so pair with a gentle routine if needed.",
    why: "A homegrown Malaysian option balancing scalp care and everyday cleansing.",
  },
  {
    id: "dove-1min-smooth",
    name: "Dove 1 Minute Miracle",
    brand: "Dove",
    category: "Shampoo",
    priceRange: "RM15–26",
    budgetMax: 26,
    market: "MY",
    tags: ["smoothing", "conditioning", "moisture"],
    keyIngredients: ["Keratin Repair", "Argan Oil", "Glycerin"],
    normalizedIngredients: ["water", "sodium laureth sulfate", "sodium lauryl sulfate", "glycerin", "fragrance"],
    bestFor: ["Rough hair", "Damage", "Affordable smoothing"],
    considerations:
      "Affordable smoothing-focused formula. Sulfate-based; fine for most but dry scalps may want a gentler alternate.",
    why: "Cost-effective smoothing suited to rough or damaged hair without overspending.",
  },
];
