import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// The website and database seed share this reviewed source of truth.
const catalogue = JSON.parse(readFileSync(new URL("../src/data/shampoos.my.json", import.meta.url), "utf8"));
const quote = (v) => v === null ? "null" : typeof v === "boolean" || typeof v === "number" ? String(v) : "'" + String(v).replaceAll("'", "''") + "'";
function upsert(table, record) {
  const keys = Object.keys(record);
  return `insert into public.${table} (${keys.join(", ")}) values (${keys.map((k) => quote(record[k])).join(", ")}) on conflict (id) do update set ${keys.filter((k) => k !== "id").map((k) => `${k} = excluded.${k}`).join(", ")};`;
}
const statements = ["-- GENERATED by node scripts/catalogue-seed.mjs; edit src/data/shampoos.my.json instead.", "-- Online source snapshots, not physical-bottle verification or live inventory.", "begin;"];
for (const p of catalogue.products) {
  const f = p.formulation, l = p.listing;
  statements.push(upsert("catalogue_products", { id: p.id, brand: p.brand, name: p.name, market: p.market, tags: JSON.stringify(p.tags), claim: p.claim, catalogue_version: catalogue.version }));
  statements.push(upsert("catalogue_formulations", { id: f.id, product_id: p.id, ingredients: f.ingredients, ingredients_complete: f.ingredientsComplete, contains_fragrance: f.fragrance, source_url: f.sourceUrl, source_name: f.sourceName, reviewed_at: f.reviewedAt, status: f.status, note: f.note }));
  statements.push(upsert("catalogue_listings", { id: l.id, product_id: p.id, formulation_id: f.id, retailer: l.retailer, size: p.size, url: l.url, price: l.price, regular_price: l.regularPrice, currency: l.currency, observed_at: l.observedAt, stock: l.stock, affiliate: l.affiliate }));
}
statements.push("commit;", "");
const target = new URL("../supabase/seed_shampoos.sql", import.meta.url);
writeFileSync(target, statements.join("\n"));
console.log(`Prepared ${catalogue.products.length} products, formulations and listings: ${fileURLToPath(target)}`);
